#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pathname'
require 'fileutils'
# rubocop:disable Style/MixinUsage
include(FileUtils::Verbose)
# rubocop:enable Style/MixinUsage

Dir['/boot/{.[^\.]*,*}']
  .reject { |fp| Pathname.new(fp).mountpoint? }
  .sort.each { |fp| rm_rf(fp) }
