#!/usr/bin/env ruby
# coding: utf-8
# frozen_string_literal: true

require 'pathname'
require 'fileutils'
# rubocop:disable Style/MixinUsage
include(FileUtils::Verbose)
# rubocop:enable Style/MixinUsage

Pathname.new('/var/log').tap do |logdir|
  logdir.join('lastlog').tap do |lastlog|
    touch(lastlog)
    chown('root', 'utmp', lastlog)
  end

  logdir.join('secure').tap do |seclog|
    Pathname.new('/etc/syslog.conf').tap do |config|
      if config.file? and config.readable?
        if /\s+#{seclog}\s*$/ =~ config.read
          touch(seclog)
          chmod(0o640, seclog)
        end
      end
    end
  end

  logdir.join('ylem').tap do |logfile|
    chmod(0o640, logfile) if logfile.file?
  end
end

[1, 2].each do |c|
  Pathname.new('/proc/1/fd').join(c.to_s).tap do |fp|

  end
end
