#!/usr/bin/env ruby
# frozen_string_literal: true

# noinspection RubyResolve
$LOAD_PATH.unshift('/boot/lib/ruby').tap { require 'boot' }

# Execute setup
if __FILE__ == $PROGRAM_NAME
  at_exit { GC.start }

  Boot::Services::Setup.new.call
end
