#!/usr/bin/env ruby
# frozen_string_literal: true

# noinspection RubyResolve
require '/boot/lib/ruby/boot/services'

# Execute setup
if __FILE__ == $PROGRAM_NAME
  at_exit { GC.start }

  Boot::Services::Setup.new.call
end
