#!/usr/bin/env ruby
# frozen_string_literal: true

# noinspection RubyResolve
require '/boot/lib/ruby/boot'

# Execute setup
if __FILE__ == $PROGRAM_NAME
  at_exit { GC.start }

  exit(0) unless Boot::Services::Setup.new.config.key?(:ssh)

  Boot::ThreadPool.new do |pool|
    [Boot::SSH::Auth, Boot::Dropbear::Setup].map do |klass|
      pool.schedule { klass.new.call }
    end
  end.call
end
