#!/usr/bin/env ruby
# frozen_string_literal: true

# noinspection RubyResolve
require '/boot/lib/ruby/boot'

# Execute setup
if __FILE__ == $PROGRAM_NAME
  at_exit { GC.start }

  Boot::Services::Setup.new.config.key?(:ssh).tap do |flag|
    if flag
      Boot::ThreadPool.new do |pool|
        [Boot::SSH::Auth, Boot::SSH::DropbearSetup].map do |klass|
          pool.schedule { klass.new.call }
        end
      end.call
    end
  end
end
