#!/usr/bin/env ruby
# frozen_string_literal: true

ENV['SVDIR'].tap do |svdir|
  if svdir.to_s.empty?
    warn('SVDIR must be set')
    exit(Errno::ECANCELED::Errno) # 125
  end

  ['runsvdir', '-P', svdir].map(&:to_s).tap do |cmd|
    File.open(File::NULL, 'w').tap { |stdin| STDIN = stdin }
    exec(*cmd)
  end
end
