#!/usr/bin/env ruby
# frozen_string_literal: true

require 'shellwords'

ENV['SVDIR'].tap do |svdir|
  if svdir.to_s.empty?
    warn('SVDIR must be set')
    exit(Errno::ECANCELED::Errno) # 125
  end

  Shellwords.join(['runsvdir', '-P', svdir])
            .tap { |cmd| exec("#{cmd} < /dev/null") }
end
