#!/usr/bin/env ruby
# coding: utf-8
# frozen_string_literal: true
# rubocop:disable Style/AsciiComments

# Setup ``dropbear`` server
#
# Sample config directory structure:
#
# ```
# /etc/dropbear/
# ├── allow
# │   └── root
# ├── host_rsa
# └── host_rsa.pem
# ```
#
# ``host_rsa`` file SHOULD be mounted, or it will be generated
# it can be converted from a PEM file (``host_rsa.pem``).
# Files found in ``/etc/dropbear/allow`` will be copied,
# to the corresponding users ``.ssh`` directories.
#
# ```sh
# yes | ssh-keygen \
#      -t rsa -b 4096 -N '' \
#     -f host_rsa.pem -m PEM -C "your_email@example.com"
# ```
class DropbearSetup
  autoload :Etc, 'etc'
  autoload :Pathname, 'pathname'
  autoload :Shellwords, 'shellwords'
  autoload :FileUtils, 'fileutils'

  # Get directory
  #
  # @return [Pathname]
  attr_reader :directory

  # Dropbear private key
  #
  # @return [Pathname]
  attr_reader :host_key

  # PEM RSA private key
  #
  # @return [Pathname]
  attr_reader :host_pem

  def initialize(directory = ENV['DROPBEAR_CONFDIR'])
    @directory = Pathname.new(directory || '/etc/dropbear')

    @host_key = Pathname.new('host_rsa')
    @host_pem = Pathname.new("#{@host_key}.pem")

    @futils = FileUtils::Verbose
  end

  # Get commands.
  #
  # #return [Hash{Symbol => Array<Object>}]
  def commands
    {
      convert: ['dropbearconvert', 'openssh', 'dropbear', host_pem, host_key],
      generate: ['dropbearkey', '-f', host_key, '-t', :rsa],
    }
  end

  # @return [String]
  def to_path
    directory.to_path
  end

  # @return [self]
  def call
    self.to_path.tap do |directory|
      futils.mkdir_p(directory)
      Dir.chdir(directory) do
        convert_pem
        gen_key

        apply_perms
        authorize
      end
    end

    self
  end

  # @return [Hash{Pathname => Etc::Passwd}]
  def authorizables
    Dir.glob('allow/*')
       .map { |f| Pathname.new(f) }.keep_if(&:file?).map do |file|
      begin
        [file, Etc.getpwnam(file.basename.to_s)]
      rescue ArgumentError => e
        warn(e.message)
      end
    end.compact.to_h
  end

  protected

  # @return [FileUtils]
  attr_accessor :futils

  # Convert pem file.
  #
  # @return [self]
  def convert_pem
    commands.fetch(:convert).tap do |cmd|
      if host_pem.file? and host_pem.readable?
        futils.chmod(0o600, host_pem)
        sh(*cmd.map(&:to_s))
      end
    end

    self
  end

  # Create private key used with dropbear.
  #
  # #param [String|Symbol] type
  # @return [self]
  #
  # @see http://manpages.ubuntu.com/manpages/precise/man8/dropbearkey.8.html
  # @see https://www.mail-archive.com/dropbear@ucc.asn.au/msg01689.html
  def gen_key
    commands.fetch(:generate).tap do |cmd|
      cmd.push('-y') if host_key.file?

      sh(*cmd.map(&:to_s))
      futils.chmod(0o600, host_key)
    end

    self
  end

  # @return self
  def apply_perms
    futils.chmod(0o700, 'allow') if Pathname.new('allow').directory?

    authorizables.keys.each do |file|
      begin
        futils.chmod(0o600, file) if file.file?
      rescue StandardError => e
        warn(e.message)
      end
    end
  end

  # Dispatch authorized_keys files.
  #
  # @return [self]
  def authorize
    authorizables.each do |file, user|
      begin
        Pathname.new("#{user.dir}/.ssh/authorized_keys")
                .tap { |target| copy_auth(file, target, user) }
      rescue StandardError => e
        warn(e.message)
      end
    end

    self
  end

  # @param [Pathname|String] file
  # @param [Pathname] target
  # @param [Etc::Passwd] user
  def copy_auth(file, target, user = nil)
    futils.mkdir_p(target.dirname)
    futils.chmod(0o700, target.dirname)
    futils.cp(file, target)

    futils.chmod(0o600, target)
    futils.chown(user.uid, user.gid, target) if user
  end

  # @raise [Errno::EOPNOTSUPP]
  # @return [Boolean]
  def sh(*command)
    warn(Shellwords.join(command))

    system(*command).tap do |res|
      return res if res

      "#{Shellwords.join(command)} [#{$CHILD_STATUS.exitstatus}]".tap do |s|
        raise Errno::EOPNOTSUPP, s
      end
    end
  end
end

if __FILE__ == $PROGRAM_NAME
  DropbearSetup.new.call
end

# rubocop:enable Style/AsciiComments
