#!/usr/bin/env ruby
# frozen_string_literal: true

require 'sv/utils/cli'
require 'yaml'
require 'pathname'
require 'fileutils'

Pathname.new('/etc/service.yml').tap do |config|
  exit 0 unless config.file? and config.readable?

  ENV.fetch('SVDIR').tap do |svdir|
    Dir.glob("#{svdir}/*").each { |fp| FileUtils.rm_rf(svdir) }
    FileUtils.mkdir_p(svdir, mode: 0o755)
  end

  YAML.safe_load(config.read).each do |name, auto|
    ['enable', name.to_s, '--%<no>sauto-start' % {
      no: auto ? '' : 'no-'
    }].tap do |args|
      Sv::Utils::CLI.call(:control, args)
    end
  end
end
