FROM alpine:3.7
MAINTAINER Dimitri Arrigoni <dimitri@arrigoni.me>

# Set environment
ENV LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    EDITOR=vim \
    PATH=/opt/local/bin:/opt/local/sbin:$PATH \
    INITRD=no
